import type { Metadata, Viewport } from "next";
import { Providers } from "./providers";
import "@/globals.css";
import { Inter } from "next/font/google";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export async function generateMetadata(): Promise<Metadata> {
  const URL = process.env.NEXT_PUBLIC_URL!;

  return {
    title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
    description:
      "Generated by `create-onchain --mini`, a Next.js template for MiniKit",
    other: {
      "fc:frame": JSON.stringify({
        version: process.env.NEXT_PUBLIC_VERSION,
        imageUrl: URL + process.env.NEXT_PUBLIC_IMAGE_URL,
        button: {
          title: `Launch ${process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME}`,
          action: {
            splashBackgroundColor: `#${process.env.NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR}`,
            splashImageUrl: URL + process.env.NEXT_PUBLIC_SPLASH_IMAGE_URL,
            name: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
            type: "launch_frame",
            url: URL,
          },
        },
      }),
    },
  };
}

const font = Inter({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"bg-background overflow-hidden" + font.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
